
CMINPACK=lmder.c dpmpar.c enorm.c qrfac.c lmpar.c qrsolv.c

LMSOLVER=lmsolver.C objectives.C

FULLGDSOLVER=fullgdsolver.C adam.C

LBFGSSOLVER=lbfgs.c

GDSOLVER=gdsolver.C adam.C

LTA=lta_file.C myltasub.c mycorrsub.c sort.c

MISC=gaintable.C models.C logsolve.C ants.C

fullpolphaselbfgsunity: fullpolphaselbfgsunity.C $(LBFGSSOLVER) 
	g++ -static -O0 -o $@ -g -std=c++11 -DLBFGS_FLOAT=32 -DLBFGS_IEEE_FLOAT=1 -DTIMING  fullpolphaselbfgsunity.C LBFGSsingle_unpolarized.C LBFGSleakage_unpolarized.C $(LBFGSSOLVER) $(LTA) $(MISC) 
	#g++ -static -O0 -o $@ -g -DCHANDEBUG -DDPRINT -std=c++11 -DLBFGS_FLOAT=32 -DLBFGS_IEEE_FLOAT=1 -DTIMING  fullpolphaselbfgsunity.C LBFGSparallel.C LBFGSfull_unpolarized.C $(LBFGSSOLVER) $(LTA) $(MISC) 
	#g++ -O2 -o $@ -g -fopenmp -std=c++11 -DLBFGS_FLOAT=32 -DLBFGS_IEEE_FLOAT=1 -DTIMING  fullpolphaselbfgsunity.C LBFGSparallel.C LBFGSfull_unpolarized.C $(LBFGSSOLVER) $(LTA) $(MISC) 

diagpolphaselbfgsleakage: diagpolphaselbfgsleakage.C $(LBFGSSOLVER) 
	g++ -static -O0 -o $@ -g -std=c++11 -DLBFGS_FLOAT=32 -DLBFGS_IEEE_FLOAT=1 -DTIMING  diagpolphaselbfgsleakage.C LBFGSparallel_polarized.C $(LBFGSSOLVER) $(LTA) $(MISC) 
